# coding: utf-8

"""
Alteryx Server API V3

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from src.server_client.configuration import Configuration


class DCMEObjectWrapperContractDCMECredentialContract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"object": "DCMECredentialContract"}

    attribute_map = {"object": "object"}

    def __init__(self, object=None, _configuration=None):  # noqa: E501
        """DCMEObjectWrapperContractDCMECredentialContract - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._object = None
        self.discriminator = None

        self.object = object

    @property
    def object(self):
        """Gets the object of this DCMEObjectWrapperContractDCMECredentialContract.  # noqa: E501


        :return: The object of this DCMEObjectWrapperContractDCMECredentialContract.  # noqa: E501
        :rtype: DCMECredentialContract
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this DCMEObjectWrapperContractDCMECredentialContract.


        :param object: The object of this DCMEObjectWrapperContractDCMECredentialContract.  # noqa: E501
        :type: DCMECredentialContract
        """
        if self._configuration.client_side_validation and object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501

        self._object = object

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(DCMEObjectWrapperContractDCMECredentialContract, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DCMEObjectWrapperContractDCMECredentialContract):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DCMEObjectWrapperContractDCMECredentialContract):
            return True

        return self.to_dict() != other.to_dict()
