# coding: utf-8

"""
Alteryx Server API V3

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from src.server_client.configuration import Configuration


class DeletedDataSourceView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"id": "str", "deleted_on": "datetime"}

    attribute_map = {"id": "id", "deleted_on": "deletedOn"}

    def __init__(self, id=None, deleted_on=None, _configuration=None):  # noqa: E501
        """DeletedDataSourceView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._deleted_on = None
        self.discriminator = None

        self.id = id
        self.deleted_on = deleted_on

    @property
    def id(self):
        """Gets the id of this DeletedDataSourceView.  # noqa: E501


        :return: The id of this DeletedDataSourceView.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeletedDataSourceView.


        :param id: The id of this DeletedDataSourceView.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def deleted_on(self):
        """Gets the deleted_on of this DeletedDataSourceView.  # noqa: E501


        :return: The deleted_on of this DeletedDataSourceView.  # noqa: E501
        :rtype: datetime
        """
        return self._deleted_on

    @deleted_on.setter
    def deleted_on(self, deleted_on):
        """Sets the deleted_on of this DeletedDataSourceView.


        :param deleted_on: The deleted_on of this DeletedDataSourceView.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and deleted_on is None:
            raise ValueError("Invalid value for `deleted_on`, must not be `None`")  # noqa: E501

        self._deleted_on = deleted_on

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(DeletedDataSourceView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeletedDataSourceView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DeletedDataSourceView):
            return True

        return self.to_dict() != other.to_dict()
