# coding: utf-8

"""
Alteryx Server API V3

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from src.server_client.configuration import Configuration


class IterationDailyContract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"run_only_work_week": "bool"}

    attribute_map = {"run_only_work_week": "runOnlyWorkWeek"}

    def __init__(self, run_only_work_week=None, _configuration=None):  # noqa: E501
        """IterationDailyContract - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._run_only_work_week = None
        self.discriminator = None

        if run_only_work_week is not None:
            self.run_only_work_week = run_only_work_week

    @property
    def run_only_work_week(self):
        """Gets the run_only_work_week of this IterationDailyContract.  # noqa: E501


        :return: The run_only_work_week of this IterationDailyContract.  # noqa: E501
        :rtype: bool
        """
        return self._run_only_work_week

    @run_only_work_week.setter
    def run_only_work_week(self, run_only_work_week):
        """Sets the run_only_work_week of this IterationDailyContract.


        :param run_only_work_week: The run_only_work_week of this IterationDailyContract.  # noqa: E501
        :type: bool
        """

        self._run_only_work_week = run_only_work_week

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(IterationDailyContract, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IterationDailyContract):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IterationDailyContract):
            return True

        return self.to_dict() != other.to_dict()
